[package]
name = "kira-editor"
authors = ["sajid <sysajid98@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
log = "0.4.14"